configmap:
  backend:
    name: backend-config
    DB_HOST: bdd-svc.default.svc.cluster.local
    DEBUG: '"False"'
  bdd:
    name: bdd-config 
  frontend:
    name: frontend-config
  nginx:
    name: nginx-config

deployment:
  backend:
    name: backend-deploy
    image: amadka/gestion-depense-backend
    tag: 98238f854320ec264332e366ef8b46eba9e8ae28
    labels: backend
    replicasCount: 1
    ports: 8000  
  frontend:
    name: frontend-deploy
    image: amadka/gestion-depense-frontend
    tag: 98238f854320ec264332e366ef8b46eba9e8ae28
    labels: frontend
    replicasCount: 1
    ports: 3000  
  bdd:
    name: bdd
    labels: depense-bdd
    replicasCount: 1
  nginx:
    name: nginx-proxy
    labels: nginx
    replicasCount: 1
    ports: 80

service:
  backend:
    name: backend-service
    ports: 8000
    targetPort: 8000
    type: ClusterIP
  frontend:
    name: frontend-service
    ports: 3000
    targetPort: 3000
    type: ClusterIP
  bdd:
    name: bdd-svc
    type: ClusterIP
  nginx:
    name: nginx-svc
    ports: 80
    targetPort: 80
    type: ClusterIP