apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployment.backend.labels }}
  name: {{ .Values.deployment.backend.name }}
spec:
  replicas: {{ .Values.deployment.backend.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.backend.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.backend.labels }}
    spec:
      containers:
      - image: {{ .Values.deployment.backend.image }}
        name: gestion-depense-backend
        ports:
          - containerPort: {{ .Values.deployment.backend.ports }}
        envFrom:
          - configMapRef:
              name: {{ .Values.configmap.backend.name }}
        volumeMounts:
        - name: static-volume
          mountPath: /app/staticfiles
        resources:
          requests:
            cpu: 20m
            memory: 80Mi
          limits:
            cpu: 100m
            memory: 150Mi
      resources: {}
      volumes:
      - name: static-volume
        emptyDir: {}
status: {}
