apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployment.frontend.labels }}
  name: {{ .Values.deployment.frontend.name }}
spec:
  replicas: {{ .Values.deployment.frontend.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.frontend.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.frontend.labels }}
    spec:
      containers:
      - image: "{{ .Values.deployment.frontend.image }}:{{ .Values.deployment.frontend.tag }}"
        name: gestion-depense-frontend
        ports:
          - containerPort: {{ .Values.deployment.frontend.ports }}
        envFrom:
          - configMapRef:
              name: {{ .Values.configmap.frontend.name }}
        resources:
          requests:
            cpu: 50m
            memory: 60Mi
          limits:
            cpu: 150m
            memory: 120Mi
status: {}
