apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployment.nginx.labels }}
  name: {{ .Values.deployment.nginx.name }}
spec:
  replicas: {{ .Values.deployment.nginx.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.nginx.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.nginx.labels }}
    spec:
      containers:
      - image: nginx:stable-alpine
        name: nginx
        ports:
          - containerPort: {{ .Values.deployment.nginx.ports }}
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: static-volume
            mountPath: /static
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 30m
            memory: 40Mi
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Values.configmap.nginx.name }}
        - name: static-volume
          emptyDir: {}
status: {}
