apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.frontend.name }}
            port:
              number: {{ .Values.service.frontend.ports }}
      
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.backend.name }}
            port:
              number: {{ .Values.service.backend.ports }}
      
      # Nginx sert les statics
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.nginx.name }}
            port:
              number: {{ .Values.service.nginx.ports }}